/*---------------------------------------------------------
  The options statement below should be placed
  before the data step when submitting this code.
---------------------------------------------------------*/
options VALIDMEMNAME=EXTEND VALIDVARNAME=ANY;
   /*------------------------------------------
   Generated SAS Scoring Code
     Date             : 30May2024:07:38:05
     Locale           : en_US
     Model Type       : Decision Tree
     Interval variable: Price per Unit
     Interval variable: Total Sales
     Interval variable: Units Sold
     Class variable   : Sales_Level
     Response variable: Sales_Level
     ------------------------------------------*/
   /*---------------------------------------------------------
   SAS Code Generated by Cloud Analytic Services for Decision Tree
     Date                  : 30May2024:11:38:05 UTC
     Number of Nodes       : 23
     Number of Tree Depth  : 6
     Number of Bins        : 50
     Number of Obs         : 7917
     -------------------------------------------------------*/

   array _tlevname_10787_{2} $4 _temporary_ ( 'High' 
   'Low');

   array _dt_fi_10787_{2} _temporary_;

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_10787:
   if _node_id_ eq 0 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 17500 and _numval_ lt 82500) then do;

            _new_id_ = 1;
         end;
         else if (_numval_ ge 0 and _numval_ lt 17500) then do;

            _new_id_ = 2;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 2;
         end;
         else if (_numval_ ge 82500) then do;
            _new_id_ = 1;
         end;
         else do;
         _new_id_ = 2;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _leaf_id_ = 1;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =                    1;
         _dt_fi_10787_{1} =                    0; 
         _dt_fi_10787_{2} =                    1; 
   end;
   else if _node_id_ eq 2 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 163 and _numval_ lt 1275) then do;

            _new_id_ = 3;
         end;
         else if (_numval_ ge 0 and _numval_ lt 163) then do;

            _new_id_ = 4;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 4;
         end;
         else if (_numval_ ge 1275) then do;
            _new_id_ = 3;
         end;
         else do;
         _new_id_ = 4;
         end;
   end;
   else if _node_id_ eq 3 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 9625 and _numval_ lt 82500) then do;

            _new_id_ = 5;
         end;
         else if (_numval_ ge 0 and _numval_ lt 9625) then do;

            _new_id_ = 6;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 6;
         end;
         else if (_numval_ ge 82500) then do;
            _new_id_ = 5;
         end;
         else do;
         _new_id_ = 6;
         end;
   end;
   else if _node_id_ eq 4 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 70 and _numval_ lt 110) then do;

            _new_id_ = 7;
         end;
         else if (_numval_ ge 7 and _numval_ lt 70) then do;

            _new_id_ = 8;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 8;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 7;
         end;
         else do;
         _new_id_ = 8;
         end;
   end;
   else if _node_id_ eq 5 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 450 and _numval_ lt 1275) then do;

            _new_id_ = 9;
         end;
         else if (_numval_ ge 0 and _numval_ lt 450) then do;

            _new_id_ = 10;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 10;
         end;
         else if (_numval_ ge 1275) then do;
            _new_id_ = 9;
         end;
         else do;
         _new_id_ = 10;
         end;
   end;
   else if _node_id_ eq 6 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 174 and _numval_ lt 1275) then do;

            _new_id_ = 11;
         end;
         else if (_numval_ ge 0 and _numval_ lt 174) then do;

            _new_id_ = 12;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 12;
         end;
         else if (_numval_ ge 1275) then do;
            _new_id_ = 11;
         end;
         else do;
         _new_id_ = 11;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _numval_ = 'Total Sales'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 1048.84 and _numval_ lt 82500) then do;

            _new_id_ = 13;
         end;
         else if (_numval_ ge 0 and _numval_ lt 1048.84) then do;

            _new_id_ = 14;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 14;
         end;
         else if (_numval_ ge 82500) then do;
            _new_id_ = 13;
         end;
         else do;
         _new_id_ = 14;
         end;
   end;
   else if _node_id_ eq 8 then do;
         _leaf_id_ = 8;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =                    1;
         _dt_fi_10787_{1} =                    1; 
         _dt_fi_10787_{2} =                    0; 
   end;
   else if _node_id_ eq 9 then do;
         _numval_ = 'Units Sold'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 525 and _numval_ lt 1275) then do;

            _new_id_ = 15;
         end;
         else if (_numval_ ge 0 and _numval_ lt 525) then do;

            _new_id_ = 16;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 16;
         end;
         else if (_numval_ ge 1275) then do;
            _new_id_ = 15;
         end;
         else do;
         _new_id_ = 16;
         end;
   end;
   else if _node_id_ eq 10 then do;
         _leaf_id_ = 10;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.97125567322239;
         _dt_fi_10787_{1} =     0.97125567322239; 
         _dt_fi_10787_{2} =      0.0287443267776; 
   end;
   else if _node_id_ eq 11 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 55 and _numval_ lt 110) then do;

            _new_id_ = 17;
         end;
         else if (_numval_ ge 7 and _numval_ lt 55) then do;

            _new_id_ = 18;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 18;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 17;
         end;
         else do;
         _new_id_ = 18;
         end;
   end;
   else if _node_id_ eq 12 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 66 and _numval_ lt 110) then do;

            _new_id_ = 19;
         end;
         else if (_numval_ ge 7 and _numval_ lt 66) then do;

            _new_id_ = 20;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 20;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 19;
         end;
         else do;
         _new_id_ = 20;
         end;
   end;
   else if _node_id_ eq 13 then do;
         _leaf_id_ = 13;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =      0.8235294117647;
         _dt_fi_10787_{1} =     0.17647058823529; 
         _dt_fi_10787_{2} =      0.8235294117647; 
   end;
   else if _node_id_ eq 14 then do;
         _numval_ = 'Price per Unit'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 80 and _numval_ lt 110) then do;

            _new_id_ = 21;
         end;
         else if (_numval_ ge 7 and _numval_ lt 80) then do;

            _new_id_ = 22;
         end;
         else if (_numval_ lt 7) then do;
            _new_id_ = 22;
         end;
         else if (_numval_ ge 110) then do;
            _new_id_ = 21;
         end;
         else do;
         _new_id_ = 22;
         end;
   end;
   else if _node_id_ eq 15 then do;
         _leaf_id_ = 15;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =                0.875;
         _dt_fi_10787_{1} =                0.125; 
         _dt_fi_10787_{2} =                0.875; 
   end;
   else if _node_id_ eq 16 then do;
         _leaf_id_ = 16;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =      0.7027027027027;
         _dt_fi_10787_{1} =      0.7027027027027; 
         _dt_fi_10787_{2} =     0.29729729729729; 
   end;
   else if _node_id_ eq 17 then do;
         _leaf_id_ = 17;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.53618421052631;
         _dt_fi_10787_{1} =     0.46381578947368; 
         _dt_fi_10787_{2} =     0.53618421052631; 
   end;
   else if _node_id_ eq 18 then do;
         _leaf_id_ = 18;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.52624212736179;
         _dt_fi_10787_{1} =     0.52624212736179; 
         _dt_fi_10787_{2} =      0.4737578726382; 
   end;
   else if _node_id_ eq 19 then do;
         _leaf_id_ = 19;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.63636363636363;
         _dt_fi_10787_{1} =     0.36363636363636; 
         _dt_fi_10787_{2} =     0.63636363636363; 
   end;
   else if _node_id_ eq 20 then do;
         _leaf_id_ = 20;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.91620111731843;
         _dt_fi_10787_{1} =     0.91620111731843; 
         _dt_fi_10787_{2} =     0.08379888268156; 
   end;
   else if _node_id_ eq 21 then do;
         _leaf_id_ = 21;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.83333333333333;
         _dt_fi_10787_{1} =     0.16666666666666; 
         _dt_fi_10787_{2} =     0.83333333333333; 
   end;
   else if _node_id_ eq 22 then do;
         _leaf_id_ = 22;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.96666666666666;
         _dt_fi_10787_{1} =     0.96666666666666; 
         _dt_fi_10787_{2} =     0.03333333333333; 
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_10787;
   end;

   I_Sales_Level = _tlevname_10787_{_dt_pred_lev_+1};
   label I_Sales_Level = 'Into: Sales_Level';
   _i_ = 1;
   _dt_predp_ = _dt_fi_10787_{_i_};
   P_Sales_LevelHigh = _dt_predp_;
   label P_Sales_LevelHigh = 'Predicted: Sales_Level=High';
   _i_+1;
   _dt_predp_ = _dt_fi_10787_{_i_};
   P_Sales_LevelLow = _dt_predp_;
   label P_Sales_LevelLow = 'Predicted: Sales_Level=Low';
   _i_+1;
   drop _dt_predp_;
   drop _i_;
   drop _dt_pred_lev_;
   drop _dt_pred_prob_;
   drop _numval_;
   drop _node_id_;
   drop _new_id_;
   /*------------------------------------------*/
   /*_VA_DROP*/ drop 'I_Sales_Level'n '_leaf_id_'n 'P_Sales_LevelHigh'n 'P_Sales_LevelLow'n;
length 'I_Sales_Level_10787_2'n $4;
      'I_Sales_Level_10787_2'n='I_Sales_Level'n;
'P_Sales_LevelHigh_10787_2'n='P_Sales_LevelHigh'n;
'P_Sales_LevelLow_10787_2'n='P_Sales_LevelLow'n;
'_leaf_id__10787_2'n='_leaf_id_'n;
   /*------------------------------------------*/